name: chicago-crime-simple
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pyspark==3.5.1
      - pandas==2.2.2
      - scikit-learn==1.5.1
      - pyarrow==17.0.0
      - pyyaml==6.0.2
      - pytest==8.3.3
